package com.example.jtorrent.rss;

import org.junit.jupiter.api.*;

import java.net.URI;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Simple tests for RSSFeed.
 */
@DisplayName("RSSFeed Tests")
class RSSFeedTest {

    @Nested
    @DisplayName("Construction Tests")
    class ConstructionTests {

        @Test
        @DisplayName("Should create feed with name and URL")
        void shouldCreateFeedWithNameAndUrl() throws Exception {
            URI url = new URI("http://example.com/feed.rss");
            RSSFeed feed = new RSSFeed("Test Feed", url);

            assertNotNull(feed);
            assertEquals("Test Feed", feed.getName());
            assertEquals(url, feed.getUrl());
        }

        @Test
        @DisplayName("Should have auto-generated ID")
        void shouldHaveAutoGeneratedId() throws Exception {
            RSSFeed feed = new RSSFeed("Test", new URI("http://example.com/feed.rss"));

            assertNotNull(feed.getId());
            assertFalse(feed.getId().isEmpty());
        }

        @Test
        @DisplayName("Should be enabled by default")
        void shouldBeEnabledByDefault() throws Exception {
            RSSFeed feed = new RSSFeed("Test", new URI("http://example.com/feed.rss"));

            assertTrue(feed.isEnabled());
        }
    }

    @Nested
    @DisplayName("Name Tests")
    class NameTests {

        @Test
        @DisplayName("Should set name")
        void shouldSetName() throws Exception {
            RSSFeed feed = new RSSFeed("Old Name", new URI("http://example.com/feed.rss"));

            feed.setName("New Name");

            assertEquals("New Name", feed.getName());
        }
    }

    @Nested
    @DisplayName("URL Tests")
    class UrlTests {

        @Test
        @DisplayName("Should set URL")
        void shouldSetUrl() throws Exception {
            RSSFeed feed = new RSSFeed("Test", new URI("http://old.com/feed.rss"));
            URI newUrl = new URI("http://new.com/feed.rss");

            feed.setUrl(newUrl);

            assertEquals(newUrl, feed.getUrl());
        }
    }

    @Nested
    @DisplayName("Refresh Interval Tests")
    class RefreshIntervalTests {

        @Test
        @DisplayName("Should have default refresh interval")
        void shouldHaveDefaultRefreshInterval() throws Exception {
            RSSFeed feed = new RSSFeed("Test", new URI("http://example.com/feed.rss"));

            assertTrue(feed.getRefreshIntervalMinutes() > 0);
        }

        @Test
        @DisplayName("Should set refresh interval")
        void shouldSetRefreshInterval() throws Exception {
            RSSFeed feed = new RSSFeed("Test", new URI("http://example.com/feed.rss"));

            feed.setRefreshIntervalMinutes(60);

            assertEquals(60, feed.getRefreshIntervalMinutes());
        }
    }

    @Nested
    @DisplayName("Enable/Disable Tests")
    class EnableDisableTests {

        @Test
        @DisplayName("Should disable feed")
        void shouldDisableFeed() throws Exception {
            RSSFeed feed = new RSSFeed("Test", new URI("http://example.com/feed.rss"));

            feed.setEnabled(false);

            assertFalse(feed.isEnabled());
        }

        @Test
        @DisplayName("Should enable feed")
        void shouldEnableFeed() throws Exception {
            RSSFeed feed = new RSSFeed("Test", new URI("http://example.com/feed.rss"));
            feed.setEnabled(false);

            feed.setEnabled(true);

            assertTrue(feed.isEnabled());
        }
    }

    @Nested
    @DisplayName("Last Fetch Time Tests")
    class LastFetchTimeTests {

        @Test
        @DisplayName("Should track last fetch time")
        void shouldTrackLastFetchTime() throws Exception {
            RSSFeed feed = new RSSFeed("Test", new URI("http://example.com/feed.rss"));
            long now = System.currentTimeMillis();

            feed.setLastFetchTime(now);

            assertEquals(now, feed.getLastFetchTime());
        }
    }

    @Nested
    @DisplayName("Error Tracking Tests")
    class ErrorTrackingTests {

        @Test
        @DisplayName("Should track last error")
        void shouldTrackLastError() throws Exception {
            RSSFeed feed = new RSSFeed("Test", new URI("http://example.com/feed.rss"));

            feed.setLastError("Connection timeout");

            assertEquals("Connection timeout", feed.getLastError());
        }

        @Test
        @DisplayName("Should clear last error")
        void shouldClearLastError() throws Exception {
            RSSFeed feed = new RSSFeed("Test", new URI("http://example.com/feed.rss"));
            feed.setLastError("Error");

            feed.setLastError(null);

            assertNull(feed.getLastError());
        }
    }
}
